#!/usr/bin/env python3
"""Generate auto-derived LaTeX/PGFPlots figures from data/.

Outputs (paper/figures/):
  - gap-dotplot.tex          per-product highway-range gap, ordered, color-coded
  - severity-heatmap.tex     products × axes severity matrix
  - recall-bars.tex          NHTSA recall counts by product
  - tactic-prevalence.tex    cross-manufacturer tactic recurrence
  - source-tier-sankey.tex   evidence-source flow by tier

Run from repo root: .venv/bin/python paper/figures/generate.py
All figures are standalone TikZ pictures wrapped in `tikzpicture` so they can
be \\input{}-ed directly into main.tex.
"""
from __future__ import annotations

import json
from collections import Counter, defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DATA = REPO / "data"
OUT = REPO / "paper" / "figures"


def load_products() -> dict:
    return {p.stem: json.loads(p.read_text()) for p in (DATA / "products").glob("*.json")}


def load_deceptions() -> list:
    return [json.loads(p.read_text()) for p in (DATA / "deceptions").glob("*.json")]


def load_tactics() -> dict:
    return {t.stem: json.loads(t.read_text()) for t in (DATA / "tactics").glob("*.json")}


SEVERITY_COLOR = {
    "critical": "red!80!black",
    "high": "orange!85!black",
    "moderate": "yellow!75!black",
    "low": "green!50!black",
    "informational": "blue!60!black",
}
SEVERITY_RANK = {"critical": 0, "high": 1, "moderate": 2, "low": 3, "informational": 4}


def short_label(p: dict) -> str:
    """Compact axis label: 'Tesla M3 LR AWD' style."""
    mfg = {"Mercedes-Benz": "Mercedes", "Volkswagen": "VW"}.get(p["manufacturer"], p["manufacturer"])
    model = p["model"].replace("F-150 Lightning", "F-150 Lt").replace("Mustang Mach-E", "Mach-E")
    model = model.replace("Hummer EV Pickup", "Hummer EV").replace("Cybertruck", "CT")
    trim = p["trim"][:18]
    return f"{mfg} {model} {p['model_year']}"


# --------------------------------------------------------------------------- #
# Figure 1 — per-product highway-range gap dotplot                            #
# --------------------------------------------------------------------------- #
def fig_gap_dotplot(products: dict, decs: list) -> str:
    rows = []
    for d in decs:
        if d["axis"] != "range" or "highway" not in d["sub_axis"]:
            continue
        gap = d.get("gap", {})
        if gap.get("kind") != "numeric" or gap.get("pct") is None:
            continue
        p = products.get(d["product_id"])
        if not p:
            continue
        rows.append({
            "label": short_label(p),
            "pct": gap["pct"],
            "severity": gap.get("severity", "informational"),
            "claim": d["claim"]["value"],
            "reality": d["reality"]["value"],
            "grade": d.get("evidence_grade", "B"),
        })
    rows.sort(key=lambda r: r["pct"])
    n = len(rows)
    yticks = ",".join(str(i) for i in range(1, n + 1))
    yticklabels = "{" + ",".join(r["label"] for r in rows) + "}"
    coords = " ".join(f"({r['pct']},{i+1})" for i, r in enumerate(rows))
    color_marks = "\n".join(
        f"      \\addplot[only marks, mark=*, mark size=4.5pt, line width=0.6pt, "
        f"color={SEVERITY_COLOR[r['severity']]}, fill={SEVERITY_COLOR[r['severity']]}] "
        f"coordinates {{({r['pct']},{i+1})}};"
        for i, r in enumerate(rows)
    )

    tex = rf"""% Auto-generated by paper/figures/generate.py — do not edit by hand
\begin{{tikzpicture}}
  \begin{{axis}}[
      width=0.95\textwidth, height=0.55\textwidth,
      xlabel={{Real-world (70\,mph) gap vs.\ EPA combined (\%)}},
      xmin=-35, xmax=15,
      ymin=0.5, ymax={n + 0.5},
      ytick={{{yticks}}},
      yticklabels={yticklabels},
      grid=major,
      grid style={{dashed,gray!30}},
      tick label style={{font=\footnotesize}},
      xlabel style={{font=\footnotesize}},
      x tick label style={{/pgf/number format/fixed,/pgf/number format/precision=0}},
      every axis plot/.append style={{very thick}},
    ]
    \draw[gray!50, dashed] (axis cs:0,0.5) -- (axis cs:0,{n + 0.5});
{color_marks}
  \end{{axis}}
\end{{tikzpicture}}
"""
    return tex


# --------------------------------------------------------------------------- #
# Figure 2 — severity heatmap (products × axes)                               #
# --------------------------------------------------------------------------- #
def fig_severity_heatmap(products: dict, decs: list) -> str:
    AXES = ["range", "charging", "performance", "software_features", "pricing", "production_status", "ui_ergonomics", "build_warranty"]
    AXIS_SHORT = {
        "range": "Range",
        "charging": "Charging",
        "performance": "Perf.",
        "software_features": "Software",
        "pricing": "Pricing",
        "production_status": "Status",
        "ui_ergonomics": "UI",
        "build_warranty": "Recalls",
    }
    pids = sorted(products.keys(), key=lambda k: short_label(products[k]))
    cell = defaultdict(lambda: 9)  # default = no record
    for d in decs:
        sev = d.get("gap", {}).get("severity")
        rank = SEVERITY_RANK.get(sev, 9)
        key = (d["product_id"], d["axis"])
        cell[key] = min(cell[key], rank)

    coords_by_sev = defaultdict(list)
    for j, pid in enumerate(pids):
        for i, ax in enumerate(AXES):
            r = cell.get((pid, ax), 9)
            if r >= 9:
                continue
            sev_name = next(k for k, v in SEVERITY_RANK.items() if v == r)
            coords_by_sev[sev_name].append((i, j))

    addplots = []
    for sev, coords in coords_by_sev.items():
        c = " ".join(f"({x},{y})" for x, y in coords)
        addplots.append(
            f"      \\addplot[only marks, mark=square*, mark size=8pt, "
            f"color={SEVERITY_COLOR[sev]}] coordinates {{{c}}};"
        )
    addplots_tex = "\n".join(addplots)
    xticklabels = "{" + ",".join(AXIS_SHORT[a] for a in AXES) + "}"
    yticklabels = "{" + ",".join(short_label(products[pid]) for pid in pids) + "}"

    tex = rf"""% Auto-generated by paper/figures/generate.py
\begin{{tikzpicture}}
  \begin{{axis}}[
      width=\textwidth, height=0.6\textwidth,
      xtick={{0,...,{len(AXES)-1}}}, xticklabels={xticklabels},
      ytick={{0,...,{len(pids)-1}}}, yticklabels={yticklabels},
      x tick label style={{rotate=30, anchor=east, font=\scriptsize}},
      y tick label style={{font=\scriptsize}},
      xmin=-0.5, xmax={len(AXES)-0.5},
      ymin=-0.5, ymax={len(pids)-0.5},
      grid=major, grid style={{very thin, gray!20}},
      enlargelimits=false,
      axis on top,
    ]
{addplots_tex}
  \end{{axis}}
\end{{tikzpicture}}
"""
    return tex


# --------------------------------------------------------------------------- #
# Figure 3 — NHTSA recall counts                                              #
# --------------------------------------------------------------------------- #
def fig_recall_bars(products: dict) -> str:
    rows = []
    for pid, p in products.items():
        n = p.get("nhtsa", {}).get("recall_count", 0)
        rows.append((short_label(p), n))
    rows.sort(key=lambda r: -r[1])
    coords = " ".join(f"({r[1]},{i+1})" for i, r in enumerate(rows))
    yticks = ",".join(str(i) for i in range(1, len(rows) + 1))
    yticklabels = "{" + ",".join(r[0] for r in rows) + "}"
    nodes = "\n".join(
        f"    \\node[anchor=west, font=\\footnotesize] at (axis cs:{r[1]+0.2},{i+1}) {{{r[1]}}};"
        for i, r in enumerate(rows)
    )

    tex = rf"""% Auto-generated by paper/figures/generate.py
\begin{{tikzpicture}}
  \begin{{axis}}[
      width=0.85\textwidth, height=0.55\textwidth,
      xbar, xmin=0, xmax={max(r[1] for r in rows)+2},
      ymin=0.5, ymax={len(rows)+0.5},
      ytick={{{yticks}}}, yticklabels={yticklabels},
      xlabel={{NHTSA recall campaigns (model year as documented)}},
      tick label style={{font=\scriptsize}},
      xlabel style={{font=\footnotesize}},
      bar width=10pt,
      nodes near coords align={{horizontal}},
      grid=major, grid style={{dashed,gray!30}},
    ]
    \addplot[fill=red!60!black, draw=red!50!black] coordinates {{{coords}}};
{nodes}
  \end{{axis}}
\end{{tikzpicture}}
"""
    return tex


# --------------------------------------------------------------------------- #
# Figure 4 — Cross-manufacturer tactic prevalence (RQ2)                       #
# --------------------------------------------------------------------------- #
def fig_tactic_prevalence(products: dict, decs: list, tactics: dict) -> str:
    by_tactic_mfg = defaultdict(set)
    for d in decs:
        p = products.get(d["product_id"])
        if not p:
            continue
        for t in d.get("tactic_ids", []):
            by_tactic_mfg[t].add(p["manufacturer"])
    rows = [(t, len(mfgs)) for t, mfgs in by_tactic_mfg.items()]
    rows.sort(key=lambda r: -r[1])
    rows = rows[:10]  # top 10
    yticks = ",".join(str(i) for i in range(1, len(rows) + 1))
    # Use \texttt for monospace tactic IDs; preserve underscores via _ → \_ for LaTeX
    def latex_id(t: str) -> str:
        return r"\texttt{" + t.replace("_", r"\_") + "}"
    yticklabels = "{" + ",".join(latex_id(t) for t, _ in rows) + "}"
    coords = " ".join(f"({n},{i+1})" for i, (_, n) in enumerate(rows))
    nodes = "\n".join(
        f"    \\node[anchor=west, font=\\footnotesize] at (axis cs:{n+0.1},{i+1}) {{{n}}};"
        for i, (_, n) in enumerate(rows)
    )
    xmax_val = max(r[1] for r in rows) + 2

    tex = rf"""% Auto-generated by paper/figures/generate.py
\begin{{tikzpicture}}
  \begin{{axis}}[
      width=\textwidth, height=0.55\textwidth,
      xbar, xmin=0, xmax={xmax_val},
      ymin=0.5, ymax={len(rows)+0.5},
      ytick={{{yticks}}}, yticklabels={yticklabels},
      xlabel={{Distinct manufacturers in which the tactic appears}},
      tick label style={{font=\scriptsize}},
      yticklabel style={{anchor=east, align=right}},
      xlabel style={{font=\footnotesize}},
      bar width=10pt,
      enlarge y limits=0.06,
      grid=major, grid style={{dashed,gray!25}},
      x post scale=1.0,
      y axis line style={{draw=none}},
    ]
    \addplot[fill=blue!55!black, draw=blue!40!black] coordinates {{{coords}}};
{nodes}
  \end{{axis}}
\end{{tikzpicture}}
"""
    return tex


# --------------------------------------------------------------------------- #
# Figure 5 — Source-tier Sankey                                                #
# --------------------------------------------------------------------------- #
def fig_source_sankey(decs: list) -> str:
    """Counts records by tier composition: T1+T2 (claim Tier-1 vs reality Tier-2), etc."""
    pairs = Counter()
    for d in decs:
        ct = min((s.get("tier", 4) for s in d.get("claim", {}).get("sources", [])), default=4)
        rt = min((s.get("tier", 4) for s in d.get("reality", {}).get("sources", [])), default=4)
        pairs[(ct, rt)] += 1

    # Render as a small TikZ flow with proportional widths (we use sankey package)
    # For minimal complexity, emit a side-by-side bar with arrows summarizing flow.
    # (Full sankey would require the sankey package and more setup.)
    total = sum(pairs.values())
    claim_dist = Counter()
    reality_dist = Counter()
    for (c, r), n in pairs.items():
        claim_dist[c] += n
        reality_dist[r] += n

    HCOL = 8.0  # cm — column height
    BAR_W = 1.2
    GAP = 4.0
    def fmt_dist(label: str, dist: Counter, x: float) -> str:
        cum = 0
        out = []
        for tier in sorted(dist.keys()):
            n = dist[tier]
            h = HCOL * n / total
            color = ["", "blue!70", "green!60!black", "orange!70", "gray!50"][tier]
            out.append(
                rf"\fill[{color}] ({x},{cum}) rectangle ({x+BAR_W},{cum+h});"
                rf"\node[font=\footnotesize, white] at ({x+BAR_W/2},{cum+h/2}) {{T{tier} ({n})}};"
            )
            cum += h
        out.append(rf"\node[font=\footnotesize\bfseries, anchor=north] at ({x+BAR_W/2},-0.3) {{{label}}};")
        return "\n  ".join(out)

    arrows = []
    cum_claim_pos = defaultdict(float)
    cum_real_pos = defaultdict(float)
    for (c, r), n in sorted(pairs.items()):
        h = HCOL * n / total
        # rough Bezier between claim column at right edge (x=1) and reality column at left edge (x=4)
        y_c_start = sum(HCOL * claim_dist[t] / total for t in sorted(claim_dist.keys()) if t < c) + cum_claim_pos[c]
        y_r_start = sum(HCOL * reality_dist[t] / total for t in sorted(reality_dist.keys()) if t < r) + cum_real_pos[r]
        cum_claim_pos[c] += h
        cum_real_pos[r] += h
        c_color = ["", "blue!40", "green!30!black", "orange!40", "gray!30"][c]
        x_left = BAR_W
        x_right = x_left + GAP
        arrows.append(
            rf"\fill[{c_color}, opacity=0.45] ({x_left},{y_c_start}) "
            rf".. controls ({x_left+GAP/2},{y_c_start}) and ({x_left+GAP/2},{y_r_start}) "
            rf".. ({x_right},{y_r_start}) -- ({x_right},{y_r_start+h}) "
            rf".. controls ({x_left+GAP/2},{y_r_start+h}) and ({x_left+GAP/2},{y_c_start+h}) "
            rf".. ({x_left},{y_c_start+h}) -- cycle;"
        )

    tex = rf"""% Auto-generated by paper/figures/generate.py
\begin{{tikzpicture}}[scale=0.85]
  {fmt_dist("Claim source", claim_dist, 0.0)}
  {fmt_dist("Reality source", reality_dist, BAR_W + GAP)}
  {chr(10).join(arrows)}
\end{{tikzpicture}}
"""
    return tex


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    products = load_products()
    decs = load_deceptions()
    tactics = load_tactics()

    figs = {
        "gap-dotplot.tex": fig_gap_dotplot(products, decs),
        "severity-heatmap.tex": fig_severity_heatmap(products, decs),
        "recall-bars.tex": fig_recall_bars(products),
        "tactic-prevalence.tex": fig_tactic_prevalence(products, decs, tactics),
        "source-tier-sankey.tex": fig_source_sankey(decs),
    }
    for name, tex in figs.items():
        (OUT / name).write_text(tex)
        print(f"✓ {name}")


if __name__ == "__main__":
    main()
